#!/usr/bin/env bash
# This is a dummy mpirun, it doesn't doe anything but showing you the arguments
echo $@  # | sed "s/--[^[:space:]]*//g" | sed "s/-[^[:space:]]*[[:space:]][^[:space:]]*//g" | bash -s
